require "diegognt.launch"
require "diegognt.options"
require "diegognt.keymaps"
require "diegognt.autocommands"
-- Specs goes here
spec "diegognt.colorscheme"
spec "diegognt.treesitter"
spec "diegognt.mason"
spec "diegognt.lsp"
spec "diegognt.lsp.diagnostic"
spec "diegognt.lsp.notifications"
spec "diegognt.navic"
spec "diegognt.breadcrumbs"
spec "diegognt.completion"
spec "diegognt.none-ls"
spec "diegognt.test"
spec "diegognt.telescope"
spec "diegognt.lualine"
spec "diegognt.autopairs"
spec "diegognt.comments"
spec "diegognt.indentation"
spec "diegognt.whichkey"
spec "diegognt.greeter"
spec "diegognt.extras.devicons"
spec "diegognt.extras.annotation"
spec "diegognt.extras.copilot"
spec "diegognt.extras.harpoon"
spec "diegognt.extras.oil"
spec "diegognt.extras.folding"
spec "diegognt.extras.todo-manager"
-- Specs ends here
require "diegognt.lazy"
-- require('diegognt.plugins')
-- require('diegognt.gitsigns')
-- require('diegognt.toggleterm')
-- require('diegognt.impatient')
-- require('diegognt.illuminate')
