return {
  ensure_installed = {
    'astro',
    'bash',
    'c',
    'cmake',
    'cpp',
    'css',
    'dockerfile',
    'dot',
    'git_config',
    'git_rebase',
    'gitattributes',
    'gitcommit',
    'gitignore',
    'go',
    'graphql',
    'html',
    'javascript',
    'jsdoc',
    'json',
    'lua',
    'luadoc',
    'luap',
    'make',
    'markdown',
    'markdown_inline',
    'php',
    'phpdoc',
    'prisma',
    'pug',
    'python',
    'query',
    'regex',
    'scss',
    'terraform',
    'toml',
    'tsx',
    'typescript',
    'vim',
    'vimdoc',
    'yaml',
  },
  sync_install = false, -- install languages synchronously (only applied to `ensure_installed`)
  autopairs = {
    enable = true,
  },
  highlight = {
    enable = true, -- false will disable the whole extension
    disable = { '' }, -- list of language that will be disabled
    additional_vim_regex_highlighting = true,
  },
  indent = {
    enable = true,
    disable = { 'yaml' },
  },
  context_commentstring = {
    enable = true,
    enable_autocmd = false,
  },
  autotag = { -- `Uses windwp/nvim-ts-autotag` to autoclose or autoremane HTML tags.
    enable = true,
  },
}
